export const BucketMap: any =
  {
    'default': 'dev-dra-us-west-2-723398989493',
    'development': 'dev-dra-us-west-2-723398989493',
    'production': 'dra-us-west-2-723398989493',
    'state': 'dra-us-west-2-723398989493',
    'state-dev': 'dev-dra-us-west-2-723398989493',
    'logs': 'dra-uswest-logs',
    'memsqs': 'dra-uswest-memsqs',
    'images': 'dra-uswest-images',
    'data': 'dra-us-west-datafiles',
    'data-dev': 'dra-us-west-datafiles-dev',
    'splits': 'dra-block-cache',
    'splits-dev': 'dra-block-cache-dev',
    'counties': 'dra-county-cache',
    'counties-dev': 'dra-county-cache',
    'geojson': 'dra-uswest-geojson',
    'geojson-dev': 'dra-uswest-geojson',
    'transfers': 'dra-transfers',
    'transfers-dev': 'dra-transfers-dev',
  }
